import type { NextPage, GetStaticProps, InferGetStaticPropsType } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ArticleCard } from "../components/ArticleCard/ArticleCard";
import { fetchContent } from "../utils/contentful/fetchContent";
import getLocale from "../utils/contentful/getLocale";

export type ArticleProps = {
  sys: {
    id: string;
  };
  title: string;
  slug: string;
  category: string;
  image: string;
  heroImage: {
    url: string;
  };
};

const GET_ALL_ARTICLES_WITH_LOCALE = `
  query ($locale: String!) {
    articleCollection (locale: $locale) {
      items {
        sys {
          id
        }
        title
        slug
        category
        heroImage {
          url
        }
      }
    }
  }
`;

export const getStaticProps: GetStaticProps = async (params) => {
  const { locale } = params;
  const localeParams = getLocale(locale);

  const data = await fetchContent(GET_ALL_ARTICLES_WITH_LOCALE, {
    locale: localeParams,
  });
  const articles = data.articleCollection.items;

  return {
    props: {
      articles,
    },
    revalidate: 5,
  };
};

const Home: NextPage = ({
  articles,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to the Masters</h1>
        {articles &&
          articles.map((article: ArticleProps) => (
            <ArticleCard
              key={article.sys.id}
              title={article.title}
              slug={article.slug}
              category={article.category}
              image={article.heroImage.url}
            />
          ))}
      </main>
    </div>
  );
};

export default Home;
