import Head from "next/head";
import { GetStaticProps, NextPage } from "next";
import { CanvasClient, EnhancerBuilder, compose } from "@uniformdev/canvas";
import { createClient } from "contentful";
// import { Slot, Composition } from "@uniformdev/canvas-react";
import {
  CANVAS_CONTENTFUL_PARAMETER_TYPES,
  createContentfulEnhancer,
} from "@uniformdev/canvas-contentful";
import { fetchContent } from "../utils/contentful/fetchContent";
import getLocale from "../utils/contentful/getLocale";
import { GET_ALL_ARTICLES_WITH_LOCALE } from "../queries/contentful/graphqlQueries";
import ArticleList from "../components/ArticleList/ArticleList";
import styles from "../styles/Home.module.css";
import { ArticlesProps } from "../components/ArticleList/type";
import HomePageCTA from "../components/HomePageCTA/HomePageCTA";

export const getStaticProps: GetStaticProps = async (params) => {
  // UNIFORM
  const client = new CanvasClient({
    apiKey: process.env.UNIFORM_API_KEY,
    projectId: process.env.UNIFORM_PROJECT_ID,
  });
  const { composition } = await client.getCompositionBySlug({
    slug: "homepage",
  });
  const { locale } = params;
  const localeParams = getLocale(locale);

  // CONTENTFUL
  const contentfulClient = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    environment: "master",
    accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
  });
  const contentfulEnhancer = createContentfulEnhancer({
    client: contentfulClient,
  });
  const enhancer = new EnhancerBuilder().parameterType(
    CANVAS_CONTENTFUL_PARAMETER_TYPES,
    compose(contentfulEnhancer, ({ parameter }) => {
      const { fields } = parameter.value;
      parameter.value = fields;
      return parameter.value;
    })
  );
  console.log(enhancer);
  const data = await fetchContent(GET_ALL_ARTICLES_WITH_LOCALE, {
    locale: localeParams,
  });
  const articles = data.newsArticleCollection.items;
  return {
    props: {
      articles,
      composition,
    },
    revalidate: 5,
  };
};

const Home: NextPage = ({ articles, composition }: ArticlesProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePageCTA />
      <ArticleList articles={articles} />
    </div>
  );
};

export default Home;
