import type { NextPage, GetStaticProps, InferGetStaticPropsType } from "next";
import Head from "next/head";
import { createClient } from "contentful";
import styles from "../styles/Home.module.css";
import { ArticleCard } from "../components/ArticleCard/ArticleCard";

export const getStaticProps: GetStaticProps = async () => {
  // Contentful client
  const client = createClient({
    space: process.env.SPACE_ID,
    accessToken: process.env.ACCESS_TOKEN,
  });

  const response = await client.getEntries({ content_type: "article" });

  return {
    props: {
      articles: response.items,
    },
    revalidate: 60,
  };
};

const Home: NextPage = ({
  articles,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to the Masters</h1>
        {articles &&
          articles.map((article) => (
            <ArticleCard
              key={article.sys.id}
              title={article.fields.title}
              slug={article.fields.slug}
              category={article.fields.category}
              image={article.fields.heroImage.fields.file.url}
            />
          ))}
      </main>
    </div>
  );
};

export default Home;
